train_model:
  RandomForestRegressor:
    max_depth:
    - 5
    - 8
    max_features:
    - 5
    - 7
    n_estimators:
    - 50
    - 100
    - 150
  XGBRegressor:
    learning_rate:
    - 0.01
    - 0.1
    max_depth:
    - 5
    - 8
    - 6
    n_estimators:
    - 100
    - 200
base_model_score: '0.6'
